# Generated by Django 3.1.5 on 2021-04-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210419_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='author',
        ),
    ]
